#!/bin/bash

CONF_DIR="/srv/data/LAVA/config"
LAVA_DIR=$(ls / | grep lava)
LAVA_PROXY="/$LAVA_DIR/bin/lava-proxy"
NFSSERVER=$1

source $LAVA_PROXY
echo "[  INFO  ] Set proxy"

echo "[  INFO  ] Current system date is `date`"

echo "[  INFO  ] Detecting network interface"
sleep 5
while [ 1 ]; do
    interfaces=`ifconfig | grep -E 'eno[0-9]|ens[0-9]|eth[0-9]|enp[0-9]' | awk -F ': ' '{ print $1 }'`
    if [[ ! -z $interfaces ]]; then
        break
    fi
    [ "$retry" == "3" ] && break
    echo "[  RETRY  ] Detecting network interface"
    sleep 5
    retry=$(( retry+1 ))
done

for iface in $interfaces; do
    echo "[  INFO  ] Board boot up successfully. Board ipaddr is `bash lava-echo-ipv4 $iface`"
done

#echo "[  INFO  ] Install netifaces"
#pip3 install --proxy=$http_proxy netifaces

#echo "[  INFO  ] Install buildbot-worker"
#pip3 install --proxy=$http_proxy buildbot-worker
#git clone https://git.yoctoproject.org/git/yocto-autobuilder2
#git clone https://git.yoctoproject.org/git/yocto-autobuilder-helper
#buildbot-worker create-worker --umask=0o22 ~/yocto-worker $YOCTO_CONTROLLER `hostname` $BUILDBOT_PASS
#buildbot-worker start ~/yocto-worker
#if [[ $? -eq 0 ]]; then
#    echo "[  OK  ] Buildbot-worker start successfully"
#else
#   echo "[  ERROR  ] Unable to start buildbot-worker"
#fi

if [[ ! -d "/srv/data" ]]; then
    mkdir -p /srv/data
    echo "[  INFO  ] Creating a dirctory in /srv/data"
else
    echo "[  INFO  ] Directory /srv/data exists"
fi

if [[ ! -z $NFSSERVER ]]; then
    echo "[  INFO  ] Mount to NFS server: $NFSSERVER"
    mount -o rw,hard,intr $NFSSERVER:/srv/data /srv/data
    if [[ $? -eq 0 ]]; then
        echo "[  OK  ] Successfully mount to nfs server"
        mount -l | grep -i nfs
    else
        echo "[  ERROR  ] Unable to mount to nfs server"
    fi
else
    echo "[  INFO  ] NFS server is not specify"
fi

echo "[  INFO  ] Set hostname"
sed -i "s/localhost.localdomain/`hostname`/g" /etc/hosts

nvme=`ls /dev/nvme0n1`
if [[ ! -z $nvme ]]; then
    if [[ ! -d "/nvme" ]]; then
        mkdir /nvme
    fi
    mount -o relatime,rw,stripe=256 $nvme /nvme
    if [[ $? -eq 0 ]]; then
    echo "[  OK  ] Successfully mount $nvme to /nvme"
    fi
else
    echo "[ INFO ] NVME partition is not exist"
fi

#list_media=`ls /run/media`
#if [[ ! -z ${list_media} ]];
#then
#    for media in ${list_media}
#    do 
#        echo "[  INFO  ] umount /run/media/${media}"
#        umount /run/media/${media}
#    done
#else
#    echo "[  INFO  ] No media attach to device"
#fi

echo "Removed older LAVA overlay files"
find /  -maxdepth 1 -type d -name "lava*" -mtime +2 -exec rm -rf {} \;
find / -maxdepth 1 -type f -name "*overlay*" -mtime +2 -exec rm -rf {} \;
